//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCoin.Web.BlockExplorer.Wallet
{
    public partial class NewAddress
    {
        protected global::System.Web.UI.WebControls.TextBox txtWalletId;
        protected global::System.Web.UI.WebControls.Button btnGenerate;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.WebControls.Literal litAddress;
        protected global::System.Web.UI.WebControls.Literal litPath;
    }
}
