//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCoin.Web.BlockExplorer
{
    public partial class Address
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorDetail;
        protected global::System.Web.UI.WebControls.Panel pnlAddress;
        protected global::System.Web.UI.WebControls.Literal litAddress;
        protected global::System.Web.UI.WebControls.Literal litBalance;
        protected global::System.Web.UI.WebControls.Literal litTxCount;
    }
}
