//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCoin.Web.BlockExplorer
{
    public partial class Block
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorDetail;
        protected global::System.Web.UI.WebControls.Panel pnlBlock;
        protected global::System.Web.UI.WebControls.Literal litHeight;
        protected global::System.Web.UI.WebControls.Literal litHash;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor aPrevHash;
        protected global::System.Web.UI.WebControls.Literal litPrevHash;
        protected global::System.Web.UI.WebControls.Literal litMerkleRoot;
        protected global::System.Web.UI.WebControls.Literal litTimestamp;
        protected global::System.Web.UI.WebControls.Literal litTxCount;
        protected global::System.Web.UI.WebControls.Literal litSize;
        protected global::System.Web.UI.WebControls.Literal litBits;
        protected global::System.Web.UI.WebControls.Literal litNonce;
        protected global::System.Web.UI.WebControls.Repeater rptTxIds;
        protected global::System.Web.UI.WebControls.HyperLink lnkPrev;
        protected global::System.Web.UI.WebControls.HyperLink lnkNext;
    }
}
