//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCoin.Web.BlockExplorer
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litApiUrl;
        protected global::System.Web.UI.WebControls.Literal litHeight;
        protected global::System.Web.UI.WebControls.Literal litDifficulty;
        protected global::System.Web.UI.WebControls.Literal litHashRate;
        protected global::System.Web.UI.WebControls.Literal litMempool;
        protected global::System.Web.UI.WebControls.Literal litBestHash;
        protected global::System.Web.UI.WebControls.Literal litBestTime;
        protected global::System.Web.UI.WebControls.Panel pnlNoBlocks;
        protected global::System.Web.UI.WebControls.Repeater rptBlocks;
        protected global::System.Web.UI.WebControls.Panel pnlNetwork;
        protected global::System.Web.UI.WebControls.Literal litCoinName;
        protected global::System.Web.UI.WebControls.Literal litCoinSymbol;
        protected global::System.Web.UI.WebControls.Literal litNetHeight;
        protected global::System.Web.UI.WebControls.Literal litBlockCount;
        protected global::System.Web.UI.WebControls.Literal litNetDifficulty;
        protected global::System.Web.UI.WebControls.Literal litNetHashRate;
        protected global::System.Web.UI.WebControls.Literal litNetMempool;
    }
}
