//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCoin.Web.BlockExplorer
{
    public partial class Mempool
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litSize;
        protected global::System.Web.UI.WebControls.Literal litBytes;
        protected global::System.Web.UI.WebControls.Literal litFees;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptTxs;
    }
}
