//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCoin.Web.BlockExplorer
{
    public partial class Transaction
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorDetail;
        protected global::System.Web.UI.WebControls.Panel pnlTx;
        protected global::System.Web.UI.WebControls.Literal litTxId;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Literal litBlock;
        protected global::System.Web.UI.WebControls.Literal litConfirmations;
        protected global::System.Web.UI.WebControls.Literal litType;
        protected global::System.Web.UI.WebControls.Literal litInputCount;
        protected global::System.Web.UI.WebControls.Literal litOutputCount;
        protected global::System.Web.UI.WebControls.Literal litTotalOutput;
        protected global::System.Web.UI.WebControls.Literal litSize;
    }
}
